# Generated by Django 4.2.6 on 2024-12-14 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_blog_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='level',
            field=models.CharField(choices=[('Main', 'Main'), ('Ordinary', 'Ordinary'), ('Featured', 'Featured')], default='Ordinary', max_length=200),
        ),
    ]
