# Generated by Django 4.2.6 on 2024-12-14 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_blog_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='level',
            new_name='type',
        ),
    ]
